---
# Permission to look up Pod details
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: aeron-k8s-bootstrap
rules:
  # Allow reading pods to find bootstrap neighbors
  - apiGroups: [""]
    resources: [pods]
    verbs: [get, list]
---
# Serviceaccount for aeron-k8s-bootstrap to run under
apiVersion: v1
kind: ServiceAccount
metadata:
  name: aeron-k8s-bootstrap
---
# Bind the previously created role to the aeron-k8s-bootstrap service account
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: aeron-k8s-bootstrap
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: aeron-k8s-bootstrap
subjects:
  - kind: ServiceAccount
    name: aeron-k8s-bootstrap
    namespace: default
---
# A configmap to hold Aeron properties
apiVersion: v1
kind: ConfigMap
metadata:
  name: aeron-k8s-bootstrap
data:
  aeron.properties: |
    aeron.print.configuration=true
---
# A statefulset to demonstrate the created bootstrap aeron properties file
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: example-aeron-k8s-bootstrap
  labels:
    app: example-aeron-k8s-bootstrap
spec:
  replicas: 3
  selector:
    matchLabels:
      app: example-aeron-k8s-bootstrap
  template:
    metadata:
      labels:
        app: example-aeron-k8s-bootstrap
        aeron.io/media-driver: "true"
    spec:
      initContainers:
        - name: aeron-k8s-bootstrap
          image: ghcr.io/james-masson/aeron-k8s-bootstrap/aeron-k8s-bootstrap:latest
          # Don't pull, as we pre-build/pre-load the images for CI
          imagePullPolicy: Never
          env:
            # example config to alter discovery process goes here
            - name: AERON_MD_DISCOVERY_PORT
              value: "8050"

          volumeMounts:
            - name: aeron-md-config-dir
              mountPath: /etc/aeron
            - name: aeron-properties
              subPath: aeron.properties
              mountPath: /etc/aeron/aeron.properties

      containers:
        # Aeron Media Driver
        - name: media-driver
          image: ghcr.io/james-masson/aeron-k8s-bootstrap/aeronmd:latest
          args:
            - /etc/aeron/bootstrap.properties
            - /etc/aeron/aeron.properties
          # Don't pull, as we pre-build/pre-load the images for CI
          imagePullPolicy: Never
          volumeMounts:
            - mountPath: /etc/aeron
              name: aeron-md-config-dir
            - mountPath: /dev/shm
              name: dshm

        # Example Aeron consuming code
        - name: example-aeron
          image: busybox
          command:
            ["/bin/sh", "-c", "trap 'exit 0' TERM; sleep infinity & wait"]
          volumeMounts:
            - mountPath: /dev/shm
              name: dshm

      serviceAccount: aeron-k8s-bootstrap
      volumes:
        # This volume holds the configurated generated by the initcontainer
        - name: aeron-md-config-dir
          emptyDir: {}
        # This is the static configuration properties for all media-drivers
        - name: aeron-properties
          configMap:
            name: aeron-k8s-bootstrap
        # Memory-backed shared memory volume for Aeron
        - name: dshm
          emptyDir:
            medium: Memory
