---
# This configuration runs Aeron on a seperate network
# and requires Multus to already be installed
# https://github.com/k8snetworkplumbingwg/multus-cni
apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: aeron-network
spec:
  config: '{
      "cniVersion": "0.3.0",
      "plugins": [
        {
          "type": "macvlan",
          "capabilities": { "ips": true },
          "master": "eth0",
          "mode": "bridge",
          "ipam": {
            "type": "host-local",
            "subnet": "192.168.1.0/24",
            "rangeStart": "192.168.1.200",
            "rangeEnd": "192.168.1.210",
            "gateway": "192.168.1.1"
          }
        }, 
        {
          "type": "tuning",
          "capabilities": {
            "mac": true
          }
        }
      ]
    }'
---
# Permission to look up Pod details
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: aeron-k8s-bootstrap
rules:
  # Allow reading pods to find bootstrap neighbors
  - apiGroups: [""]
    resources: [pods]
    verbs: [get, list]
---
# Serviceaccount for aeron-k8s-bootstrap to run under
apiVersion: v1
kind: ServiceAccount
metadata:
  name: aeron-k8s-bootstrap
---
# Bind the previously created role to the aeron-k8s-bootstrap service account
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: aeron-k8s-bootstrap
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: aeron-k8s-bootstrap
subjects:
  - kind: ServiceAccount
    name: aeron-k8s-bootstrap
    namespace: default
---
# A configmap to hold Aeron properties
apiVersion: v1
kind: ConfigMap
metadata:
  name: aeron-k8s-bootstrap
data:
  aeron.properties: |
    aeron.print.configuration=true
---
# Pod with secondary interface, with network-name and interface name defaults (aeron-network and net1)
apiVersion: v1
kind: Pod
metadata:
  name: secondary-interface-cluster-0
  labels:
    app: secondary-interface-cluster-0
    aeron.io/media-driver: "true"
  annotations:
    k8s.v1.cni.cncf.io/networks: '[
        { "name": "aeron-network",
          "ips": [ "192.168.1.200/24" ]
        }]'
spec:
  serviceAccount: aeron-k8s-bootstrap
  volumes:
    # This volume holds the configurated generated by the initcontainer
    - name: aeron-md-config-dir
      emptyDir: {}
    # This is the static configuration properties for all media-drivers
    - name: aeron-properties
      configMap:
        name: aeron-k8s-bootstrap
    # Memory-backed shared memory volume for Aeron
    - name: dshm
      emptyDir:
        medium: Memory
  initContainers:
    - name: aeron-k8s-bootstrap
      image: ghcr.io/james-masson/aeron-k8s-bootstrap/aeron-k8s-bootstrap:latest
      # Don't pull, as we pre-build/pre-load the images for CI
      imagePullPolicy: Never
      env:
        # example config to alter discovery process goes here
        - name: AERON_MD_DISCOVERY_PORT
          value: "8050"
      volumeMounts:
        - name: aeron-md-config-dir
          mountPath: /etc/aeron
  containers:
    # Aeron Media Driver
    - name: media-driver
      image: ghcr.io/james-masson/aeron-k8s-bootstrap/aeronmd:latest
      args:
        - /etc/aeron/bootstrap.properties
        - /etc/aeron/aeron.properties
      # Don't pull, as we pre-build/pre-load the images for CI
      imagePullPolicy: Never
      volumeMounts:
        - mountPath: /etc/aeron/bootstrap.properties
          name: aeron-md-config-dir
          subPath: bootstrap.properties
        - mountPath: /etc/aeron/aeron.properties
          name: aeron-properties
          subPath: aeron.properties
        - mountPath: /dev/shm
          name: dshm

    # TODO: Example Aeron consuming code

---
apiVersion: v1
kind: Pod
metadata:
  name: secondary-interface-cluster-1
  labels:
    app: secondary-interface-cluster-1
    aeron.io/media-driver: "true"
  annotations:
    k8s.v1.cni.cncf.io/networks: '[
        { "name": "aeron-network",
          "ips": [ "192.168.1.201/24" ]
        }]'
spec:
  serviceAccount: aeron-k8s-bootstrap
  volumes:
    # This volume holds the configurated generated by the initcontainer
    - name: aeron-md-config-dir
      emptyDir: {}
    # This is the static configuration properties for all media-drivers
    - name: aeron-properties
      configMap:
        name: aeron-k8s-bootstrap
    # Memory-backed shared memory volume for Aeron
    - name: dshm
      emptyDir:
        medium: Memory
  initContainers:
    - name: aeron-k8s-bootstrap
      image: ghcr.io/james-masson/aeron-k8s-bootstrap/aeron-k8s-bootstrap:latest
      # Don't pull, as we pre-build/pre-load the images for CI
      imagePullPolicy: Never
      env:
        # example config to alter discovery process goes here
        - name: AERON_MD_DISCOVERY_PORT
          value: "8050"
      volumeMounts:
        - name: aeron-md-config-dir
          mountPath: /etc/aeron
  containers:
    # Aeron Media Driver
    - name: media-driver
      image: ghcr.io/james-masson/aeron-k8s-bootstrap/aeronmd:latest
      args:
        - /etc/aeron/bootstrap.properties
        - /etc/aeron/aeron.properties
      # Don't pull, as we pre-build/pre-load the images for CI
      imagePullPolicy: Never
      volumeMounts:
        - mountPath: /etc/aeron/bootstrap.properties
          name: aeron-md-config-dir
          subPath: bootstrap.properties
        - name: aeron-properties
          mountPath: /etc/aeron/aeron.properties
          subPath: aeron.properties
        - mountPath: /dev/shm
          name: dshm

    # TODO: Example Aeron consuming code
---
# Pod with secondary interface, with network name override (AERON_MD_SECONDARY_INTERFACE_NETWORK_NAME) as "second-network".
apiVersion: v1
kind: Pod
metadata:
  name: secondary-interface-cluster-2
  labels:
    app: secondary-interface-cluster-2
    aeron.io/media-driver: "true"
  annotations:
    k8s.v1.cni.cncf.io/networks: '[
        { "name": "aeron-network",
          "ips": [ "192.168.1.202/24" ]
        }]'
spec:
  serviceAccount: aeron-k8s-bootstrap
  volumes:
    # This volume holds the configurated generated by the initcontainer
    - name: aeron-md-config-dir
      emptyDir: {}
    # This is the static configuration properties for all media-drivers
    - name: aeron-properties
      configMap:
        name: aeron-k8s-bootstrap
    # Memory-backed shared memory volume for Aeron
    - name: dshm
      emptyDir:
        medium: Memory
  initContainers:
    - name: aeron-k8s-bootstrap
      image: ghcr.io/james-masson/aeron-k8s-bootstrap/aeron-k8s-bootstrap:latest
      # Don't pull, as we pre-build/pre-load the images for CI
      imagePullPolicy: Never
      env:
        # example config to alter discovery process goes here
        - name: AERON_MD_DISCOVERY_PORT
          value: "8050"
      volumeMounts:
        - name: aeron-md-config-dir
          mountPath: /etc/aeron

  containers:
    # Aeron Media Driver
    - name: media-driver
      image: ghcr.io/james-masson/aeron-k8s-bootstrap/aeronmd:latest
      args:
        - /etc/aeron/bootstrap.properties
        - /etc/aeron/aeron.properties
      # Don't pull, as we pre-build/pre-load the images for CI
      imagePullPolicy: Never
      volumeMounts:
        - name: aeron-md-config-dir
          mountPath: /etc/aeron/bootstrap.properties
          subPath: bootstrap.properties
        - name: aeron-properties
          subPath: aeron.properties
          mountPath: /etc/aeron/aeron.properties
        - mountPath: /dev/shm
          name: dshm

    # TODO: Example Aeron consuming code
