---
# Permission to look up Pod details
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: aeron-k8s-bootstrap
rules:
  # Allow reading pods to find bootstrap neighbors
  - apiGroups: [""]
    resources: [pods]
    verbs: [get, list]
---
# Serviceaccount for aeron-k8s-bootstrap to run under
apiVersion: v1
kind: ServiceAccount
metadata:
  name: aeron-k8s-bootstrap
---
# Bind the previously created role to the aeron-k8s-bootstrap service account
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: aeron-k8s-bootstrap
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: aeron-k8s-bootstrap
subjects:
  - kind: ServiceAccount
    name: aeron-k8s-bootstrap
    namespace: default
---
# A configmap to hold Aeron properties
apiVersion: v1
kind: ConfigMap
metadata:
  name: aeron-k8s-bootstrap
data:
  aeron.properties: |
    aeron.print.configuration=true
---
# Pod with secondary interface, with network-name override
apiVersion: v1
kind: Pod
metadata:
  name: secondary-interface-envvar-interface-cluster-0
  labels:
    app: secondary-interface-envvar-interface-cluster-0
    aeron.io/media-driver: "true"
  annotations:
    k8s.v1.cni.cncf.io/network-status: '[{"name":"aws-cni","interface":"eth0","ips":["10.0.0.1"],"default":true,"dns":{}},{"name":"aws-cni","interface":"dummy9e99c8bc34f","mac":"0","dns":{}},{"name":"custom-network","interface":"int3","ips":["10.0.0.2"],"mac":"02:4a:ef:75:4e:cf","dns":{}}]'
spec:
  initContainers:
    - name: aeron-k8s-bootstrap
      image: ghcr.io/james-masson/aeron-k8s-bootstrap/aeron-k8s-bootstrap:latest
      # Don't pull, as we pre-build/pre-load the images for CI
      imagePullPolicy: Never
      env:
        # example config to alter discovery process goes here
        - name: AERON_MD_DISCOVERY_PORT
          value: "8050"
        - name: AERON_MD_SECONDARY_INTERFACE_NAME
          value: "int3"

      volumeMounts:
        - name: aeron-md-config-dir
          mountPath: /etc/aeron
        - name: aeron-properties
          subPath: aeron.properties
          mountPath: /etc/aeron/aeron.properties

  containers:
    # Aeron Media Driver
    - name: media-driver
      image: ghcr.io/james-masson/aeron-k8s-bootstrap/aeronmd:latest
      args:
        - /etc/aeron/bootstrap.properties
        - /etc/aeron/aeron.properties
      # Don't pull, as we pre-build/pre-load the images for CI
      imagePullPolicy: Never
      volumeMounts:
        - mountPath: /etc/aeron
          name: aeron-md-config-dir
        - mountPath: /dev/shm
          name: dshm

    # Example Aeron consuming code
    - name: example-aeron
      image: busybox
      command:
        ["/bin/sh", "-c", "trap 'exit 0' TERM; sleep infinity & wait"]
      volumeMounts:
        - mountPath: /dev/shm
          name: dshm

  serviceAccount: aeron-k8s-bootstrap
  volumes:
    # This volume holds the configurated generated by the initcontainer
    - name: aeron-md-config-dir
      emptyDir: {}
    # This is the static configuration properties for all media-drivers
    - name: aeron-properties
      configMap:
        name: aeron-k8s-bootstrap
    # Memory-backed shared memory volume for Aeron
    - name: dshm
      emptyDir:
        medium: Memory
---
# Pod with secondary interface, with network-name override
apiVersion: v1
kind: Pod
metadata:
  name: secondary-interface-envvar-interface-cluster-1
  labels:
    app: secondary-interface-envvar-interface-cluster-1
    aeron.io/media-driver: "true"
  annotations:
    k8s.v1.cni.cncf.io/network-status: '[{"name":"aws-cni","interface":"eth0","ips":["10.0.1.1"],"default":true,"dns":{}},{"name":"aws-cni","interface":"dummy9e99c8bc34f","mac":"0","dns":{}},{"name":"custom-network","interface":"int3","ips":["10.0.1.2"],"mac":"02:4a:ef:75:4e:cf","dns":{}}]'
spec:
  initContainers:
    - name: aeron-k8s-bootstrap
      image: ghcr.io/james-masson/aeron-k8s-bootstrap/aeron-k8s-bootstrap:latest
      # Don't pull, as we pre-build/pre-load the images for CI
      imagePullPolicy: Never
      env:
        # example config to alter discovery process goes here
        - name: AERON_MD_DISCOVERY_PORT
          value: "8050"
        - name: AERON_MD_SECONDARY_INTERFACE_NAME
          value: "int3"

      volumeMounts:
        - name: aeron-md-config-dir
          mountPath: /etc/aeron
        - name: aeron-properties
          subPath: aeron.properties
          mountPath: /etc/aeron/aeron.properties

  containers:
    # Aeron Media Driver
    - name: media-driver
      image: ghcr.io/james-masson/aeron-k8s-bootstrap/aeronmd:latest
      args:
        - /etc/aeron/bootstrap.properties
        - /etc/aeron/aeron.properties
      # Don't pull, as we pre-build/pre-load the images for CI
      imagePullPolicy: Never
      volumeMounts:
        - mountPath: /etc/aeron
          name: aeron-md-config-dir
        - mountPath: /dev/shm
          name: dshm

    # Example Aeron consuming code
    - name: example-aeron
      image: busybox
      command:
        ["/bin/sh", "-c", "trap 'exit 0' TERM; sleep infinity & wait"]
      volumeMounts:
        - mountPath: /dev/shm
          name: dshm

  serviceAccount: aeron-k8s-bootstrap
  volumes:
    # This volume holds the configurated generated by the initcontainer
    - name: aeron-md-config-dir
      emptyDir: {}
    # This is the static configuration properties for all media-drivers
    - name: aeron-properties
      configMap:
        name: aeron-k8s-bootstrap
    # Memory-backed shared memory volume for Aeron
    - name: dshm
      emptyDir:
        medium: Memory
---
# Pod with secondary interface, with network-name override
apiVersion: v1
kind: Pod
metadata:
  name: secondary-interface-envvar-interface-cluster-2
  labels:
    app: secondary-interface-envvar-interface-cluster-2
    aeron.io/media-driver: "true"
  annotations:
    k8s.v1.cni.cncf.io/network-status: '[{"name":"aws-cni","interface":"eth0","ips":["10.0.2.1"],"default":true,"dns":{}},{"name":"aws-cni","interface":"dummy9e99c8bc34f","mac":"0","dns":{}},{"name":"custom-network","interface":"int3","ips":["10.0.2.2"],"mac":"02:4a:ef:75:4e:cf","dns":{}}]'
spec:
  initContainers:
    - name: aeron-k8s-bootstrap
      image: ghcr.io/james-masson/aeron-k8s-bootstrap/aeron-k8s-bootstrap:latest
      # Don't pull, as we pre-build/pre-load the images for CI
      imagePullPolicy: Never
      env:
        # example config to alter discovery process goes here
        - name: AERON_MD_DISCOVERY_PORT
          value: "8050"
        - name: AERON_MD_SECONDARY_INTERFACE_NAME
          value: "int3"

      volumeMounts:
        - name: aeron-md-config-dir
          mountPath: /etc/aeron
        - name: aeron-properties
          subPath: aeron.properties
          mountPath: /etc/aeron/aeron.properties

  containers:
    # Aeron Media Driver
    - name: media-driver
      image: ghcr.io/james-masson/aeron-k8s-bootstrap/aeronmd:latest
      args:
        - /etc/aeron/bootstrap.properties
        - /etc/aeron/aeron.properties
      # Don't pull, as we pre-build/pre-load the images for CI
      imagePullPolicy: Never
      volumeMounts:
        - mountPath: /etc/aeron
          name: aeron-md-config-dir
        - mountPath: /dev/shm
          name: dshm

    # Example Aeron consuming code
    - name: example-aeron
      image: busybox
      command:
        ["/bin/sh", "-c", "trap 'exit 0' TERM; sleep infinity & wait"]
      volumeMounts:
        - mountPath: /dev/shm
          name: dshm

  serviceAccount: aeron-k8s-bootstrap
  volumes:
    # This volume holds the configurated generated by the initcontainer
    - name: aeron-md-config-dir
      emptyDir: {}
    # This is the static configuration properties for all media-drivers
    - name: aeron-properties
      configMap:
        name: aeron-k8s-bootstrap
    # Memory-backed shared memory volume for Aeron
    - name: dshm
      emptyDir:
        medium: Memory
---
# No secondary interface on this pod. Its primary interface should be used (status.PodIP)
apiVersion: v1
kind: Pod
metadata:
  name: secondary-interface-client
  labels:
    app: secondary-interface-client
    aeron.io/media-driver: "true"
spec:
  initContainers:
    - name: aeron-k8s-bootstrap
      image: ghcr.io/james-masson/aeron-k8s-bootstrap/aeron-k8s-bootstrap:latest
      # Don't pull, as we pre-build/pre-load the images for CI
      imagePullPolicy: Never
      env:
        # example config to alter discovery process goes here
        - name: AERON_MD_DISCOVERY_PORT
          value: "8050"
        - name: AERON_MD_SECONDARY_INTERFACE_NAME
          value: "int3"

      volumeMounts:
        - name: aeron-md-config-dir
          mountPath: /etc/aeron
        - name: aeron-properties
          subPath: aeron.properties
          mountPath: /etc/aeron/aeron.properties

  containers:
    # Aeron Media Driver
    - name: media-driver
      image: ghcr.io/james-masson/aeron-k8s-bootstrap/aeronmd:latest
      args:
        - /etc/aeron/bootstrap.properties
        - /etc/aeron/aeron.properties
      # Don't pull, as we pre-build/pre-load the images for CI
      imagePullPolicy: Never
      volumeMounts:
        - mountPath: /etc/aeron
          name: aeron-md-config-dir
        - mountPath: /dev/shm
          name: dshm

    # Example Aeron consuming code
    - name: example-aeron
      image: busybox
      command:
        ["/bin/sh", "-c", "trap 'exit 0' TERM; sleep infinity & wait"]
      volumeMounts:
        - mountPath: /dev/shm
          name: dshm

  serviceAccount: aeron-k8s-bootstrap
  volumes:
    # This volume holds the configurated generated by the initcontainer
    - name: aeron-md-config-dir
      emptyDir: {}
    # This is the static configuration properties for all media-drivers
    - name: aeron-properties
      configMap:
        name: aeron-k8s-bootstrap
    # Memory-backed shared memory volume for Aeron
    - name: dshm
      emptyDir:
        medium: Memory
