name: "Build and Test"
description: "Run tests and build the Go binary"

runs:
  using: composite
  steps:
    - uses: actions/setup-go@v6
      with:
        go-version: "^1.24"

    - name: Run unit tests
      shell: bash
      run: go test -v

    - name: Build
      shell: bash
      run: CGO_ENABLED=0 GOOS=linux go build

    - name: Restore Docker cache
      uses: actions/cache/restore@v4
      id: docker-cache
      with:
        path: /tmp/docker-cache
        key: docker-images-${{ runner.os }}-${{ hashFiles('Dockerfile', 'Dockerfile-aeronmd') }}
        restore-keys: |
          docker-images-${{ runner.os }}-

    - name: Start minikube
      uses: medyagh/setup-minikube@latest

    - name: Build and load containers to minikube
      shell: bash
      run: |
        set -eo pipefail
        eval $(minikube docker-env)

        # Try to load from cache if available
        if [ -f /tmp/docker-cache/aeron-k8s-bootstrap.tar ]; then
          echo "Loading aeron-k8s-bootstrap from cache..."
          docker load -i /tmp/docker-cache/aeron-k8s-bootstrap.tar
        fi

        if [ -f /tmp/docker-cache/aeronmd.tar ]; then
          echo "Loading aeronmd from cache..."
          docker load -i /tmp/docker-cache/aeronmd.tar
        fi

        # Build containers (will use cached layers if images were loaded)
        ./build_containers.sh

    - name: Deploy to minikube
      shell: bash
      run: kubectl apply -f example_usage.yml && kubectl rollout status statefulsets.apps example-aeron-k8s-bootstrap --timeout=90s

    - name: Test bootstrapping
      shell: bash
      run: ./check_bootstrap_success.sh

    - name: Prepare Docker cache
      shell: bash
      if: always()
      run: |
        set -eo pipefail
        mkdir -p /tmp/docker-cache
        eval $(minikube docker-env)

        echo "Saving Docker images to cache..."
        docker save jmips/aeron-k8s-bootstrap -o /tmp/docker-cache/aeron-k8s-bootstrap.tar
        docker save jmips/aeronmd -o /tmp/docker-cache/aeronmd.tar

    - name: Save Docker cache
      uses: actions/cache/save@v4
      if: always()
      with:
        path: /tmp/docker-cache
        key: docker-images-${{ runner.os }}-${{ hashFiles('Dockerfile', 'Dockerfile-aeronmd') }}
