name: "Build and Test"
description: "Run tests and build the Go binary"

runs:
  using: composite
  steps:
    - uses: actions/setup-go@v6
      with:
        go-version: "^1.24"

    - name: Run unit tests
      shell: bash
      run: go test -v

    - name: Build
      shell: bash
      run: CGO_ENABLED=0 GOOS=linux go build

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ github.token }}

    - name: Build and push aeron-k8s-bootstrap container
      uses: docker/build-push-action@v6
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: |
          ghcr.io/${{ github.repository }}/aeron-k8s-bootstrap:${{ github.sha }}
          ghcr.io/${{ github.repository }}/aeron-k8s-bootstrap:latest
        cache-from: type=registry,ref=ghcr.io/${{ github.repository }}/aeron-k8s-bootstrap:cache
        cache-to: type=registry,ref=ghcr.io/${{ github.repository }}/aeron-k8s-bootstrap:cache,mode=max

    - name: Build and push aeronmd container
      uses: docker/build-push-action@v6
      with:
        context: .
        file: ./Dockerfile-aeronmd
        push: true
        tags: |
          ghcr.io/${{ github.repository }}/aeronmd:${{ github.sha }}
          ghcr.io/${{ github.repository }}/aeronmd:latest
        cache-from: type=registry,ref=ghcr.io/${{ github.repository }}/aeronmd:cache
        cache-to: type=registry,ref=ghcr.io/${{ github.repository }}/aeronmd:cache,mode=max

    - name: Start minikube
      uses: medyagh/setup-minikube@latest

    - name: Load containers to minikube
      shell: bash
      run: |
        set -eo pipefail

        # Pull images from GHCR
        docker pull ghcr.io/${{ github.repository }}/aeron-k8s-bootstrap:${{ github.sha }}
        docker pull ghcr.io/${{ github.repository }}/aeronmd:${{ github.sha }}

        # Tag for local use
        docker tag ghcr.io/${{ github.repository }}/aeron-k8s-bootstrap:${{ github.sha }} jmips/aeron-k8s-bootstrap:latest
        docker tag ghcr.io/${{ github.repository }}/aeronmd:${{ github.sha }} jmips/aeronmd:latest

        # Load into minikube
        minikube image load jmips/aeron-k8s-bootstrap:latest
        minikube image load jmips/aeronmd:latest

    - name: Deploy to minikube
      shell: bash
      run: kubectl apply -f example_usage.yml && kubectl rollout status statefulsets.apps example-aeron-k8s-bootstrap --timeout=90s

    - name: Test bootstrapping
      shell: bash
      run: ./check_bootstrap_success.sh
